# Generated by Django 3.1.7 on 2021-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0003_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug_DATAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bug_ID', models.CharField(max_length=30)),
                ('title', models.TextField(null=True)),
                ('product', models.TextField(null=True)),
                ('component', models.TextField(null=True)),
                ('Type', models.TextField(null=True)),
                ('Priority', models.TextField(null=True)),
                ('Severity', models.TextField(null=True)),
                ('Status', models.TextField(null=True)),
                ('Milestone', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
