# Generated by Django 3.1.7 on 2021-05-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabc', '0004_bug_datas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bug_DATAs',
        ),
    ]
